### PR TITLE
Ensure that ports can be disabled

### LINKED ISSUE #1: NullPointerException produced when disabling a port from JMX / HTTP Bridge Settings
It is not possible to disable a port from the JMX / HTTP Bridge Settings. The text on the page says to leave port configuration empty to disable that port. Doing this does not work, and triggers a null pointer exception.

Steps to reproduce:
1. Log in as admin
2. Go to JMX / HTTP Bridge Settings
3. Remove one or both port values from the web endpoints section
4. Save settings

The settings:
Image

Log sample:
```
ERROR [Jetty-QTP-AdminConsole-10916]: org.jivesoftware.openfire.container.PluginServlet - Cannot invoke "Object.toString()" because "value" is null
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "value" is null
    at org.jivesoftware.util.SystemProperty.lambda$static$15(SystemProperty.java:150) ~[xmppserver-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
    at org.jivesoftware.util.SystemProperty.setValue(SystemProperty.java:372) ~[xmppserver-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
    at org.igniterealtime.openfire.plugins.jmxhttpbridge.web.admin.ConfigServlet.doPost(ConfigServlet.java:113) ~[?:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:523) ~[jetty-servlet-api-4.0.6.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jetty-servlet-api-4.0.6.jar:?]
```

### PR DESCRIPTION
**Pull request by guusdk**
The previous approach, where an _empty_ value for the configuration property that controls on what TCP port the webserver will be listening, caused a NullPointerException to be thrown.

In this commit, the 'disbled' state is represented by the value `-1` (rather than a missing value) in of the corresponding system properties. In the frontend, the value is still shown as absent, as that's more likely to be understood correctly by end-users.

fixes #1

### CODE REVIEW

File: src/java/org/igniterealtime/openfire/plugins/jmxhttpbridge/web/admin/ConfigServlet.java [hunk 1]
```diff
@@ -130,8 +130,8 @@ protected void doPost(HttpServletRequest request, HttpServletResponse response)
     protected void setDefaultAttributes(HttpServletRequest request, HttpServletResponse response)
     {
         request.setAttribute("isJmxEnabled", JMXManager.isEnabled());
-        request.setAttribute("port", StatsWebServer.JMXHTTPBRIDGE_WEBSERVER_PORT.getValue());
-        request.setAttribute("secureport", StatsWebServer.JMXHTTPBRIDGE_WEBSERVER_PORT_SECURE.getValue());
+        request.setAttribute("port", StatsWebServer.JMXHTTPBRIDGE_WEBSERVER_PORT.getValue() == -1 ? null : StatsWebServer.JMXHTTPBRIDGE_WEBSERVER_PORT.getValue());
+        request.setAttribute("secureport", StatsWebServer.JMXHTTPBRIDGE_WEBSERVER_PORT_SECURE.getValue() == -1 ? null : StatsWebServer.JMXHTTPBRIDGE_WEBSERVER_PORT_SECURE.getValue());
```
Comment (Fishbowler) [inline src/java/org/igniterealtime/openfire/plugins/jmxhttpbridge/web/admin/ConfigServlet.java]: Should these be `< 0` tests to be consistent with the descriptions in the i18n / javadoc?

Comment (guusdk) [reply src/java/org/igniterealtime/openfire/plugins/jmxhttpbridge/web/admin/ConfigServlet.java]: That's sensible, thanks.
